name: Type Check Code Base
on: [push, pull_request]
jobs:
  llscheck:
    name: Type Check Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Type Check Code Base
        uses: mrcjkb/lua-typecheck-action@v0
        with:
            configpath: ".luarc.json"
            directories: |
             lua
